services:
  - type: web
    name: music-bot
    env: node
    plan: free
    buildCommand: apt-get update && apt-get install -y python3 python3-pip && pip3 install yt-dlp && npm install
    startCommand: npm start
    envVars:
      - key: TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: RESIDENTIAL_PROXY
        sync: false
